import { RouteOption } from '../types';

/**
 * GPX 1.1 export of a route option, usable by OsmAnd, Garmin, Kurviger, etc.
 *
 * - `<trk>` carries the full road geometry of the selected graph path, so
 *   navigation apps follow the exact roads the algorithm chose.
 * - `<wpt>` entries mark the checked pin waypoints.
 */
export function routeToGpx(option: RouteOption): string {
  const name = escapeXml(option.name);

  const waypointXml = option.waypoints
    .filter(wp => wp.checked && wp.coordinates)
    .map(
      wp =>
        `  <wpt lat="${wp.coordinates!.lat}" lon="${wp.coordinates!.lon}">\n` +
        `    <name>${escapeXml(wp.location)}</name>\n` +
        `    <desc>${escapeXml(wp.description)}</desc>\n` +
        `  </wpt>`
    )
    .join('\n');

  const geometry = option.pathGeometry && option.pathGeometry.length >= 2
    ? option.pathGeometry
    : option.waypoints.filter(wp => wp.coordinates).map(wp => wp.coordinates!);

  const trackpointXml = geometry
    .map(point => `      <trkpt lat="${point.lat}" lon="${point.lon}"></trkpt>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Canyon Tour" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${name}</name>
    <desc>${escapeXml(option.description || 'Scenic route generated by Canyon Tour')}</desc>
  </metadata>
${waypointXml}
  <trk>
    <name>${name}</name>
    <trkseg>
${trackpointXml}
    </trkseg>
  </trk>
</gpx>
`;
}

/** Suggested filename for a GPX download. */
export function gpxFilename(option: RouteOption): string {
  const slug = option.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return `${slug || 'canyon_tour_route'}.gpx`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
